### PR TITLE
Colors

### PR DESCRIPTION
**Pull request by axc**
New color scheme. It's more minimalistic. Thoughts?

screen shot 2016-01-05 at 4 47 15 pm

### CODE REVIEW

**Comment by axc** [comment]
TODO: add back creep, add back old terrain

**Comment by axc** [comment]
Pressing "A" will toggle between a detailed version and the above plain version. The detailed version looks like this:
screen shot 2016-01-05 at 5 36 16 pm

**Comment by kazimuth** [comment]
Ooh, I like this.

**Comment by kazimuth** [comment]
It would be good to add a Config option for this.

**Comment by kazimuth** [comment]
When you do enable it, use `bc.client.detail` for the Config option, since that's in the scaffold.

**Comment by axc** [comment]
done

**Comment by axc** [comment]
Guards are now slightly modified to be more easily distinguishable. Photos for comparison of two clients so we can decide which one we like better (or what properties we want to keep).

screen shot 2016-01-05 at 7 36 39 pm
screen shot 2016-01-05 at 7 37 15 pm

**Comment by axc** [comment]
Ready to merge if we like the new color scheme.

**Comment by trun** [comment]
the only thing I don't like about these new sprites is the green helmet on the guards. it makes it real hard to differentiate between health bars and zombie infections in the web client, especially on larger maps where everything is scaled down. otherwise :100: these are all way easier to see.

**Comment by axc** [comment]
https://github.com/battlecode/battlecode-client/pull/68

**Pull request merged**
